# Get the RabbitMQ image with management plugin
FROM rabbitmq:management

# Set the working directory
WORKDIR /etc/rabbitmq

# Copy RabbitMQ configuration, plugins, and entry point script
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

# Expose the ports for AMQP and the management interface
EXPOSE 5672 15672 

# Set the entry point to the custom script
ENTRYPOINT ["rabbitmq-server"]
